@ASimpleForum_HostAddress = http://localhost:5059

POST {{ASimpleForum_HostAddress}}/login/
Content-Type: application/x-www-form-urlencoded
Content-Length: 35

username=johndoe&password=secure123
###
POST {{ASimpleForum_HostAddress}}/register/
Content-Type: application/x-www-form-urlencoded
Content-Length: 58

username=johndoe&password=secure123&email=johndoe@anon.com
###
POST {{ASimpleForum_HostAddress}}/logout/
Content-Type: application/x-www-form-urlencoded
Content-Length: 46

sessionId=394f201a-d0b8-4849-b0d6-7472d6d3444b
###
GET {{ASimpleForum_HostAddress}}/user?userId=johndoe
###
POST {{ASimpleForum_HostAddress}}/admin/user
Content-Type: application/x-www-form-urlencoded
Content-Length: 61

userId=johndoe&sessionId=02a32684-bb82-45ae-af3f-f45a3ce1fc51
###
POST {{ASimpleForum_HostAddress}}/mail/send/
Content-Type: application/x-www-form-urlencoded
Content-Length: 102

sessionId=abe65e15-d20c-4cd3-88f3-3b9219fdaca6&recipient=johndoe&subject=Hello World!&body=Bold of you
###
POST {{ASimpleForum_HostAddress}}/mail/inbox/
Content-Type: application/x-www-form-urlencoded
Content-Length: 110

sessionId=cf2a81e6-65a1-4413-9012-95db4b073c09&offset=0&messageLimit=10&filterUnread=false&filterFlagged=false
###
POST {{ASimpleForum_HostAddress}}/mail/msg/
Content-Type: application/x-www-form-urlencoded
Content-Length: 89

sessionId=cf2a81e6-65a1-4413-9012-95db4b073c09&msgId=cb25a3d1-c315-49ec-9a0e-91a9b5392fdb
###